name: Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      name: "tau-themes"
      archs: noarch
  sign:
    needs:
      - build
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      name: "tau-themes"
    secrets:
      signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  upload:
    needs:
      - sign
    uses: tau-OS/github-actions/.github/workflows/upload-rpm.yml@main
    with:
      name: "tau-themes"
      tauOSVersion: "1.1"
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
  packageAdwFlatpak:
    uses: tau-OS/github-actions/.github/workflows/build-flatpak.yml@main
    with:
      manifest: "flatpak/org.gtk.Gtk3theme.adw-gtk3.yaml"
    secrets:
      repoToken: ${{ secrets.FLATPAK_REPO_TOKEN }}
  packageAdwDarkFlatpak:
    uses: tau-OS/github-actions/.github/workflows/build-flatpak.yml@main
    with:
      manifest: "flatpak/org.gtk.Gtk3theme.adw-gtk3-dark.yaml"
    secrets:
      repoToken: ${{ secrets.FLATPAK_REPO_TOKEN }}
